function JSONPExample(){var W='',T=' top: -1000px;',rb='" for "gwt:onLoadErrorFn"',pb='" for "gwt:onPropertyErrorFn"',ab='");',sb='#',Eb='&',hc='.cache.js',ub='/',Ab='//',Wb='0FAEAF18163180617363374FCAB05B12',Xb='1286C647DDE95488DDF8A6D28EE7DDCB',Yb='1445268F5CD5F7F12AF77096251E5FAA',Zb='16B82E56217F1CFF21CBDFD01FA0A9AD',$b='4254A88C5722746AB17AE8830040BC95',_b='550B7A69E657F0511A5A9CEC21B919AD',ac='742528A9B5A8FE9FAF52A30D8142995C',bc='8FC4A2412F8C2D039B2C4A82CFDE4CB5',gc=':',jb='::',V='<!doctype html>',X='<html><head><\/head><body><\/body><\/html>',mb='=',tb='?',ob='Bad handler "',cc='C31E7257D0DBA00B6E4D7ABD75CE8046',dc='CFD4352C8DFD08832EDC5470D0DFF40F',U='CSS1Compat',$='Chrome',ec='D04379D97AC96DD0F70CBA397796FB29',Z='DOMContentLoaded',O='DUMMY',fc='F4683652837AA62120878C7D144ADAEF',M='JSONPExample',Ub='JSONPExample.devmode.js',yb='JSONPExample.nocache.js',ib='JSONPExample::',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',zb='base',xb='baseUrl',J='begin',P='body',I='bootstrap',wb='clear.cache.gif',lb='content',Vb='default',Cb='en',oc='end',_='eval("',Qb='gecko',Rb='gecko1_8',K='gwt.codesvr.JSONPExample=',L='gwt.codesvr=',nc='gwt/standard/standard.css',qb='gwt:onLoadErrorFn',nb='gwt:onPropertyErrorFn',kb='gwt:property',fb='head',lc='href',Pb='ie6',Ob='ie8',Nb='ie9',Q='iframe',vb='img',cb='javascript',R='javascript:""',ic='link',mc='loadExternalRefs',Bb='locale',Db='locale=',gb='meta',eb='moduleRequested',db='moduleStartup',Mb='msie',hb='name',Jb='opera',S='position:absolute; width:0; height:0; border:none; left: -1000px;',jc='rel',Lb='safari',bb='script',Tb='selectingPermutation',N='startup',kc='stylesheet',Y='undefined',Sb='unknown',Ib='user.agent',Kb='webkit';var q=window;var r=document;t(I,J);function s(){var a=q.location.search;return a.indexOf(K)!=-1||a.indexOf(L)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:M,sessionId:q.__gwtStatsSessionId,subSystem:N,evtGroup:a,millis:(new Date).getTime(),type:b})}}
JSONPExample.__sendStats=t;JSONPExample.__moduleName=M;JSONPExample.__errFn=null;JSONPExample.__moduleBase=O;JSONPExample.__softPermutationId=0;JSONPExample.__computePropValue=null;JSONPExample.__getPropMap=null;JSONPExample.__gwtInstallCode=function(){};JSONPExample.__gwtStartLoadingFragment=function(){return null};var u=function(){return false};var v=function(){return null};__propertyErrorFunction=null;var w=q.__gwt_activeModules=q.__gwt_activeModules||{};w[M]={moduleName:M};var x;function y(){A();return x}
function z(){A();return x.getElementsByTagName(P)[0]}
function A(){if(x){return}var a=r.createElement(Q);a.src=R;a.id=M;a.style.cssText=S+T;a.tabIndex=-1;r.body.appendChild(a);x=a.contentDocument;if(!x){x=a.contentWindow.document}x.open();var b=document.compatMode==U?V:W;x.write(b+X);x.close()}
function B(k){function l(a){function b(){if(typeof r.readyState==Y){return typeof r.body!=Y&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(Z,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(Z,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=z();var f=y();var g;if(navigator.userAgent.indexOf($)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(_));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(ab));g=f.createElement(bb);g.language=cb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(bb);g.language=cb;g.text=c[i];e.appendChild(g);d(e,g)}}}
JSONPExample.onScriptDownloaded=function(a){l(function(){m(a)})};t(db,eb);var n=r.createElement(bb);n.src=k;r.getElementsByTagName(fb)[0].appendChild(n)}
JSONPExample.__startLoadingFragment=function(a){return E(a)};JSONPExample.__installRunAsyncCode=function(a){var b=z();var c=y().createElement(bb);c.language=cb;c.text=a;b.appendChild(c);b.removeChild(c)};function C(){var c={};var d;var e;var f=r.getElementsByTagName(gb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(hb),k;if(j){j=j.replace(ib,W);if(j.indexOf(jb)>=0){continue}if(j==kb){k=i.getAttribute(lb);if(k){var l,m=k.indexOf(mb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=W}c[j]=l}}else if(j==nb){k=i.getAttribute(lb);if(k){try{d=eval(k)}catch(a){alert(ob+k+pb)}}}else if(j==qb){k=i.getAttribute(lb);if(k){try{e=eval(k)}catch(a){alert(ob+k+rb)}}}}}v=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;JSONPExample.__errFn=e}
function D(){function e(a){var b=a.lastIndexOf(sb);if(b==-1){b=a.length}var c=a.indexOf(tb);if(c==-1){c=a.length}var d=a.lastIndexOf(ub,Math.min(c,b));return d>=0?a.substring(0,d+1):W}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(vb);b.src=a+wb;a=e(b.src)}return a}
function g(){var a=v(xb);if(a!=null){return a}return W}
function h(){var a=r.getElementsByTagName(bb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(yb)!=-1){return e(a[b].src)}}return W}
function i(){var a=r.getElementsByTagName(zb);if(a.length>0){return a[a.length-1].href}return W}
function j(){var a=r.location;return a.href==a.protocol+Ab+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==W){k=h()}if(k==W){k=i()}if(k==W&&j()){k=e(r.location.href)}k=f(k);return k}
function E(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return JSONPExample.__moduleBase+a}
function F(){var i=[];var j;function k(a,b){var c=i;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
m[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=v(Bb)}if(!b){b=q[Fb]}if(b){c=b}while(b&&!u(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}q[Fb]=c;return b||Cb};l[Bb]={'default':0,en:1};m[Ib]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Jb)!=-1}())return Jb;if(function(){return b.indexOf(Kb)!=-1}())return Lb;if(function(){return b.indexOf(Mb)!=-1&&r.documentMode>=9}())return Nb;if(function(){return b.indexOf(Mb)!=-1&&r.documentMode>=8}())return Ob;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Pb;if(function(){return b.indexOf(Qb)!=-1}())return Rb;return Sb};l[Ib]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};u=function(a,b){return b in l[a]};JSONPExample.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};JSONPExample.__computePropValue=n;q.__gwt_activeModules[M].bindings=JSONPExample.__getPropMap;t(I,Tb);if(s()){return E(Ub)}var o;try{k([Vb,Pb],Wb);k([Cb,Nb],Xb);k([Vb,Lb],Yb);k([Vb,Ob],Zb);k([Cb,Ob],$b);k([Cb,Jb],_b);k([Vb,Nb],ac);k([Cb,Pb],bc);k([Vb,Jb],cc);k([Cb,Lb],dc);k([Cb,Rb],ec);k([Vb,Rb],fc);o=i[n(Bb)][n(Ib)];var p=o.indexOf(gc);if(p!=-1){j=parseInt(o.substring(p+1),10);o=o.substring(0,p)}}catch(a){}JSONPExample.__softPermutationId=j;return E(o+hc)}
function G(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(ic);b.setAttribute(jc,kc);b.setAttribute(lc,E(a));r.getElementsByTagName(fb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(mc,J);c(nc);t(mc,oc)}
C();JSONPExample.__moduleBase=D();w[M].moduleBase=JSONPExample.__moduleBase;var H=F();G();t(I,oc);B(H);return true}
JSONPExample.succeeded=JSONPExample();